sudo: false
language: ruby
rvm:
- 2.3.1
env:
  matrix:
  # Username and password from http://docs.travis-ci.com/user/database-setup/
  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
before_install:
- "gem install bundler --no-document"
- >-
  psql -d template1 -c "CREATE EXTENSION citext;" -U postgres
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug

# Avoid rake here, as the RSpec test task spawns a new process which does not run via bundler.
script: "bundle exec rspec --format d && bundle exec rubocop"
