dist: trusty
sudo: required
language: ruby
rvm:
# The latest ruby that is pre-installed on Travis Trusty
- 2.3.1
services:
  - postgresql
env:
  matrix:
  # https://docs.travis-ci.com/user/database-setup/#PostgreSQL
  - DB_USERNAME=postgres DB_PASSWORD=""
before_install:
- "gem update --system --no-document --quiet"
- "gem install bundler --no-document"
- "psql -d template1 -c \"CREATE EXTENSION citext;\" -U postgres"
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug

# Avoid rake here, as the RSpec test task spawns a new process which does not run via bundler.
script: "bundle exec rspec --format d && bundle exec rubocop"
